name: Build ZMK Firmware

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: zmkfirmware/zmk-actions@main
        with:
          board: nice_nano_v2
          shield: zmk_uno
          config: config
